default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: su
  host: localhost
  pool: 5

development:
  <<: *default
  database: dice_game_development

test:
  <<: *default
  database: dice_game_test

production:
  primary: &primary_production
    <<: *default
    database: dice_game_production
    username: dice_game
    password: <%= ENV["DICE_GAME_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: dice_game_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: dice_game_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: dice_game_production_cable
    migrations_paths: db/cable_migrate
